"""Configuration loading utilities for cli-mock-runtime."""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from mock_config_builder.models import MockConfig


def load_config(path: Path) -> MockConfig:
    """Load a mock configuration generated by cli-mock-generator."""

    if not path.exists():
        raise FileNotFoundError(f"Configuration file {path} not found")

    text = path.read_text(encoding="utf-8")
    data: dict
    if path.suffix.lower() in {".json"}:
        data = json.loads(text)
    else:
        data = yaml.safe_load(text)
        if data is None:
            raise ValueError("Configuration file is empty")
    return MockConfig.model_validate(data)
