"""CLI entrypoint for mock runtime server."""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import cast

import typer

if __package__ in {None, ""}:
    current_file = Path(__file__).resolve()
    package_root = current_file.parents[1]
    apps_dir = current_file.parents[2]
    for candidate in (package_root, apps_dir / "cli-mock-generator"):
        candidate_str = str(candidate)
        if candidate_str not in sys.path and candidate.exists():
            sys.path.insert(0, candidate_str)
    __package__ = "mock_server"

from .config import load_config
from .logging_utils import configure_logging
from .output_config import get_log_format, ENV_VAR_NAME, LogFormat
from .server import MockRuntime

app = typer.Typer(help="Run mock servers generated by cli-mock-generator.")


@app.command()
def serve(
    config: Path = typer.Option(
        ..., exists=True, readable=True, help="Path to mock configuration YAML/JSON file."
    ),
    log_level: str = typer.Option(
        "INFO", help="Logging level (DEBUG, INFO, WARNING, ERROR)."
    ),
    log_format: str = typer.Option(
        None,
        "--log-format",
        help=f"Log output format: 'json' or 'console'. Env: {ENV_VAR_NAME}. Default: json",
    ),
) -> None:
    """Start REST/SOAP/RPC mock servers based on configuration."""

    # Get log format with priority: CLI > ENV > default
    effective_log_format = get_log_format(log_format)
    
    logger = configure_logging(log_level, effective_log_format)

    cfg = load_config(config)
    runtime = MockRuntime(cfg)
    typer.secho(
        f"Starting mock runtime for service {cfg.service} ({len(cfg.servers)} server(s))",
        fg=typer.colors.GREEN,
    )
    logger.info(
        "runtime_starting",
        service=cfg.service,
        version=cfg.version,
        servers=len(cfg.servers),
        config_path=str(config),
        log_format=effective_log_format,
    )
    runtime.start()

    try:
        while True:  # pragma: no branch - intentionally simple loop
            time.sleep(1)
    except KeyboardInterrupt:  # pragma: no cover - manual stop
        typer.secho("Shutting down mock runtime...", fg=typer.colors.YELLOW)
        logger.info("shutdown_requested", reason="keyboard_interrupt")
    finally:
        runtime.stop()
        logger.info("runtime_stopped", service=cfg.service, servers=0)


def run() -> None:
    app()


if __name__ == "__main__":  # pragma: no cover
    run()
